//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FAMEEntities : DbContext
    {
        public FAMEEntities()
            : base("name=FAMEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<tbl_BlogPost> tbl_BlogPost { get; set; }
        public virtual DbSet<tbl_BookCode> tbl_BookCode { get; set; }
        public virtual DbSet<tbl_BookMistakes> tbl_BookMistakes { get; set; }
        public virtual DbSet<tbl_Chapter> tbl_Chapter { get; set; }
        public virtual DbSet<tbl_Comment> tbl_Comment { get; set; }
        public virtual DbSet<tbl_Conversation> tbl_Conversation { get; set; }
        public virtual DbSet<tbl_ConversationMedia> tbl_ConversationMedia { get; set; }
        public virtual DbSet<tbl_ConversationReply> tbl_ConversationReply { get; set; }
        public virtual DbSet<tbl_Coupon> tbl_Coupon { get; set; }
        public virtual DbSet<tbl_CourseDetails> tbl_CourseDetails { get; set; }
        public virtual DbSet<tbl_Courses> tbl_Courses { get; set; }
        public virtual DbSet<tbl_Document> tbl_Document { get; set; }
        public virtual DbSet<tbl_EmailLogs> tbl_EmailLogs { get; set; }
        public virtual DbSet<tbl_EnrollmentDetail> tbl_EnrollmentDetail { get; set; }
        public virtual DbSet<tbl_EnrollmentMaster> tbl_EnrollmentMaster { get; set; }
        public virtual DbSet<tbl_Exam> tbl_Exam { get; set; }
        public virtual DbSet<tbl_ExamDetail> tbl_ExamDetail { get; set; }
        public virtual DbSet<tbl_FavouriteList> tbl_FavouriteList { get; set; }
        public virtual DbSet<tbl_FileItems> tbl_FileItems { get; set; }
        public virtual DbSet<tbl_FriendRequest> tbl_FriendRequest { get; set; }
        public virtual DbSet<tbl_Friends> tbl_Friends { get; set; }
        public virtual DbSet<tbl_Installments> tbl_Installments { get; set; }
        public virtual DbSet<tbl_Master> tbl_Master { get; set; }
        public virtual DbSet<tbl_Meeting> tbl_Meeting { get; set; }
        public virtual DbSet<tbl_MeetingVideo> tbl_MeetingVideo { get; set; }
        public virtual DbSet<tbl_Notes> tbl_Notes { get; set; }
        public virtual DbSet<tbl_Options> tbl_Options { get; set; }
        public virtual DbSet<tbl_Package> tbl_Package { get; set; }
        public virtual DbSet<tbl_PackageDetail> tbl_PackageDetail { get; set; }
        public virtual DbSet<tbl_PackageDuration> tbl_PackageDuration { get; set; }
        public virtual DbSet<tbl_Progress> tbl_Progress { get; set; }
        public virtual DbSet<tbl_Question> tbl_Question { get; set; }
        public virtual DbSet<tbl_QuestionPaper> tbl_QuestionPaper { get; set; }
        public virtual DbSet<tbl_QuestionPaperDetail> tbl_QuestionPaperDetail { get; set; }
        public virtual DbSet<tbl_QuestionPartition> tbl_QuestionPartition { get; set; }
        public virtual DbSet<tbl_Ratings> tbl_Ratings { get; set; }
        public virtual DbSet<tbl_Reminder> tbl_Reminder { get; set; }
        public virtual DbSet<tbl_Request> tbl_Request { get; set; }
        public virtual DbSet<tbl_ResultDetail> tbl_ResultDetail { get; set; }
        public virtual DbSet<tbl_ResultMaster> tbl_ResultMaster { get; set; }
        public virtual DbSet<tbl_Section> tbl_Section { get; set; }
        public virtual DbSet<tbl_SectionSub> tbl_SectionSub { get; set; }
        public virtual DbSet<tbl_SeenNotif> tbl_SeenNotif { get; set; }
        public virtual DbSet<tbl_Settings> tbl_Settings { get; set; }
        public virtual DbSet<tbl_StudentGroup> tbl_StudentGroup { get; set; }
        public virtual DbSet<tbl_StudentGroupDetail> tbl_StudentGroupDetail { get; set; }
        public virtual DbSet<tbl_StudentInstallments> tbl_StudentInstallments { get; set; }
        public virtual DbSet<tbl_StudentNotif> tbl_StudentNotif { get; set; }
        public virtual DbSet<tbl_Ticket> tbl_Ticket { get; set; }
        public virtual DbSet<tbl_TicketReply> tbl_TicketReply { get; set; }
        public virtual DbSet<tbl_Tutorial> tbl_Tutorial { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tbl_UserDevices> tbl_UserDevices { get; set; }
        public virtual DbSet<tbl_UserDevRemReq> tbl_UserDevRemReq { get; set; }
        public virtual DbSet<tbl_UserLockout> tbl_UserLockout { get; set; }
        public virtual DbSet<tbl_UserLogins> tbl_UserLogins { get; set; }
        public virtual DbSet<tbl_Video> tbl_Video { get; set; }
        public virtual DbSet<vw_Roles> vw_Roles { get; set; }
        public virtual DbSet<vw_StudetsList> vw_StudetsList { get; set; }
        public virtual DbSet<tbl_DailyReport> tbl_DailyReport { get; set; }
        public virtual DbSet<tbl_QuestionSystem> tbl_QuestionSystem { get; set; }
        public virtual DbSet<tbl_DailyReportUsers> tbl_DailyReportUsers { get; set; }
        
        // Ambassador Program DbSets
        public virtual DbSet<tbl_Ambassador> tbl_Ambassador { get; set; }
        public virtual DbSet<tbl_Referral> tbl_Referral { get; set; }
        public virtual DbSet<tbl_ReferralClick> tbl_ReferralClick { get; set; }
        public virtual DbSet<tbl_ReferralConversion> tbl_ReferralConversion { get; set; }
        public virtual DbSet<tbl_AmbassadorEarning> tbl_AmbassadorEarning { get; set; }
        public virtual DbSet<tbl_CommissionRule> tbl_CommissionRule { get; set; }
        public virtual DbSet<tbl_PayoutMethod> tbl_PayoutMethod { get; set; }
        public virtual DbSet<tbl_PayoutRequest> tbl_PayoutRequest { get; set; }
        public virtual DbSet<tbl_AmbassadorAuditLog> tbl_AmbassadorAuditLog { get; set; }
    
        public virtual ObjectResult<Enrollment_Result> Enrollment(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Enrollment_Result>("Enrollment", emailParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<string> sp_GetAssistantTeacherID(string assistantID)
        {
            var assistantIDParameter = assistantID != null ?
                new ObjectParameter("AssistantID", assistantID) :
                new ObjectParameter("AssistantID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetAssistantTeacherID", assistantIDParameter);
        }
    
        public virtual ObjectResult<sp_GetConversations_Result> sp_GetConversations(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetConversations_Result>("sp_GetConversations", userIDParameter);
        }
    
        public virtual int sp_GetCoursesByStudent(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetCoursesByStudent", studentIDParameter);
        }
    
        public virtual ObjectResult<sp_GetFreeSupportAgent_Result> sp_GetFreeSupportAgent(Nullable<int> categoryID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetFreeSupportAgent_Result>("sp_GetFreeSupportAgent", categoryIDParameter);
        }
    
        public virtual ObjectResult<sp_GetPendingInstallments_Result> sp_GetPendingInstallments(Nullable<bool> isPaid, string studentFid)
        {
            var isPaidParameter = isPaid.HasValue ?
                new ObjectParameter("IsPaid", isPaid) :
                new ObjectParameter("IsPaid", typeof(bool));
    
            var studentFidParameter = studentFid != null ?
                new ObjectParameter("StudentFid", studentFid) :
                new ObjectParameter("StudentFid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPendingInstallments_Result>("sp_GetPendingInstallments", isPaidParameter, studentFidParameter);
        }
    
        public virtual ObjectResult<string> sp_GetUserEmail(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetUserEmail", userIDParameter);
        }
    
        public virtual ObjectResult<sp_GetUsersListByRole_Result> sp_GetUsersListByRole(Nullable<int> roleID, Nullable<int> categoryID, string email)
        {
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetUsersListByRole_Result>("sp_GetUsersListByRole", roleIDParameter, categoryIDParameter, emailParameter);
        }
    
        public virtual ObjectResult<sp_lstExams_Result> sp_lstExams(Nullable<int> difficultyLevel, string tags, string text, string createdBy)
        {
            var difficultyLevelParameter = difficultyLevel.HasValue ?
                new ObjectParameter("DifficultyLevel", difficultyLevel) :
                new ObjectParameter("DifficultyLevel", typeof(int));
    
            var tagsParameter = tags != null ?
                new ObjectParameter("Tags", tags) :
                new ObjectParameter("Tags", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstExams_Result>("sp_lstExams", difficultyLevelParameter, tagsParameter, textParameter, createdByParameter);
        }
    
        public virtual int sp_ResetPassword(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ResetPassword", emailParameter);
        }
    
        public virtual int sp_Truncate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Truncate");
        }
    
        public virtual int sp_ValidateCoupon(Nullable<int> iD, string secret, Nullable<bool> isCourse, Nullable<System.DateTime> date)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var secretParameter = secret != null ?
                new ObjectParameter("Secret", secret) :
                new ObjectParameter("Secret", typeof(string));
    
            var isCourseParameter = isCourse.HasValue ?
                new ObjectParameter("IsCourse", isCourse) :
                new ObjectParameter("IsCourse", typeof(bool));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ValidateCoupon", iDParameter, secretParameter, isCourseParameter, dateParameter);
        }
    
        [DbFunction("FAMEEntities", "splitstring")]
        public virtual IQueryable<string> splitstring(string stringToSplit)
        {
            var stringToSplitParameter = stringToSplit != null ?
                new ObjectParameter("stringToSplit", stringToSplit) :
                new ObjectParameter("stringToSplit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[FAMEEntities].[splitstring](@stringToSplit)", stringToSplitParameter);
        }
    
        public virtual ObjectResult<sp_GetFriendList_Result> sp_GetFriendList(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetFriendList_Result>("sp_GetFriendList", userIDParameter);
        }
    
        public virtual ObjectResult<sp_lstEnrollStatus_Result> sp_lstEnrollStatus(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, string studentID, Nullable<int> packageID, string status, Nullable<bool> isEmailSent)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var packageIDParameter = packageID.HasValue ?
                new ObjectParameter("PackageID", packageID) :
                new ObjectParameter("PackageID", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var isEmailSentParameter = isEmailSent.HasValue ?
                new ObjectParameter("IsEmailSent", isEmailSent) :
                new ObjectParameter("IsEmailSent", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstEnrollStatus_Result>("sp_lstEnrollStatus", dateFromParameter, dateToParameter, studentIDParameter, packageIDParameter, statusParameter, isEmailSentParameter);
        }
    
        public virtual ObjectResult<sp_GetAllUsersForFriendList_Result> sp_GetAllUsersForFriendList(string userID, Nullable<int> roleID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllUsersForFriendList_Result>("sp_GetAllUsersForFriendList", userIDParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<sp_GetMeetingsForStudent_Result> sp_GetMeetingsForStudent(string studentID, string status, Nullable<System.DateTime> dateFrom)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetMeetingsForStudent_Result>("sp_GetMeetingsForStudent", studentIDParameter, statusParameter, dateFromParameter);
        }
    
        public virtual ObjectResult<sp_lstDeleteDeviceReq_Result> sp_lstDeleteDeviceReq(string userID, Nullable<bool> isAccepted)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var isAcceptedParameter = isAccepted.HasValue ?
                new ObjectParameter("IsAccepted", isAccepted) :
                new ObjectParameter("IsAccepted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstDeleteDeviceReq_Result>("sp_lstDeleteDeviceReq", userIDParameter, isAcceptedParameter);
        }
    
        public virtual ObjectResult<sp_lstFavourites_Result> sp_lstFavourites(string studentID, string type)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstFavourites_Result>("sp_lstFavourites", studentIDParameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_lstVideoFaqs_Result> sp_lstVideoFaqs(Nullable<int> videoID)
        {
            var videoIDParameter = videoID.HasValue ?
                new ObjectParameter("VideoID", videoID) :
                new ObjectParameter("VideoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstVideoFaqs_Result>("sp_lstVideoFaqs", videoIDParameter);
        }
    
        public virtual ObjectResult<sp_lstComments_Result> sp_lstComments(Nullable<int> questionID, Nullable<int> videoID, Nullable<bool> isApproved)
        {
            var questionIDParameter = questionID.HasValue ?
                new ObjectParameter("QuestionID", questionID) :
                new ObjectParameter("QuestionID", typeof(int));
    
            var videoIDParameter = videoID.HasValue ?
                new ObjectParameter("VideoID", videoID) :
                new ObjectParameter("VideoID", typeof(int));
    
            var isApprovedParameter = isApproved.HasValue ?
                new ObjectParameter("IsApproved", isApproved) :
                new ObjectParameter("IsApproved", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstComments_Result>("sp_lstComments", questionIDParameter, videoIDParameter, isApprovedParameter);
        }
    
        public virtual ObjectResult<sp_lstApproveComments_Result> sp_lstApproveComments(string isApproved, string text)
        {
            var isApprovedParameter = isApproved != null ?
                new ObjectParameter("IsApproved", isApproved) :
                new ObjectParameter("IsApproved", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstApproveComments_Result>("sp_lstApproveComments", isApprovedParameter, textParameter);
        }
    
        public virtual ObjectResult<sp_GetReview_Result> sp_GetReview(Nullable<int> iD, string type, string userID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReview_Result>("sp_GetReview", iDParameter, typeParameter, userIDParameter);
        }
    
        public virtual ObjectResult<sp_GetEnrollmentByCourse_Result> sp_GetEnrollmentByCourse(string courseIDs, string packageIDs, Nullable<bool> ignoreExpiry)
        {
            var courseIDsParameter = courseIDs != null ?
                new ObjectParameter("CourseIDs", courseIDs) :
                new ObjectParameter("CourseIDs", typeof(string));
    
            var packageIDsParameter = packageIDs != null ?
                new ObjectParameter("PackageIDs", packageIDs) :
                new ObjectParameter("PackageIDs", typeof(string));
    
            var ignoreExpiryParameter = ignoreExpiry.HasValue ?
                new ObjectParameter("IgnoreExpiry", ignoreExpiry) :
                new ObjectParameter("IgnoreExpiry", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetEnrollmentByCourse_Result>("sp_GetEnrollmentByCourse", courseIDsParameter, packageIDsParameter, ignoreExpiryParameter);
        }
    
        public virtual ObjectResult<sp_SearchContent_Result> sp_SearchContent(string text)
        {
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchContent_Result>("sp_SearchContent", textParameter);
        }
    
        public virtual ObjectResult<sp_CurrentPackDetail_Result> sp_CurrentPackDetail(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CurrentPackDetail_Result>("sp_CurrentPackDetail", studentIDParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> sp_IsThisDeviceValidNow(string deviceID, string userID)
        {
            var deviceIDParameter = deviceID != null ?
                new ObjectParameter("DeviceID", deviceID) :
                new ObjectParameter("DeviceID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("sp_IsThisDeviceValidNow", deviceIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<sp_QuestionCountByStudent_Result> sp_QuestionCountByStudent(string studentID, string systemID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var systemIDParameter = systemID != null ?
                new ObjectParameter("SystemID", systemID) :
                new ObjectParameter("SystemID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_QuestionCountByStudent_Result>("sp_QuestionCountByStudent", studentIDParameter, systemIDParameter);
        }
    
        public virtual int sp_AddUserRoles(string userID, Nullable<int> roleId)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddUserRoles", userIDParameter, roleIdParameter);
        }
    
        public virtual int sp_DeleteUserRoles(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteUserRoles", userIDParameter);
        }
    
        public virtual int sp_DeleteUser(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteUser", userIDParameter);
        }
    
        public virtual ObjectResult<sp_lstQuestions_Result> sp_lstQuestions(Nullable<int> type, Nullable<int> partitionID, Nullable<int> systemID, string tags, string text, string createdBy)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            var partitionIDParameter = partitionID.HasValue ?
                new ObjectParameter("PartitionID", partitionID) :
                new ObjectParameter("PartitionID", typeof(int));
    
            var systemIDParameter = systemID.HasValue ?
                new ObjectParameter("SystemID", systemID) :
                new ObjectParameter("SystemID", typeof(int));
    
            var tagsParameter = tags != null ?
                new ObjectParameter("Tags", tags) :
                new ObjectParameter("Tags", typeof(string));
    
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstQuestions_Result>("sp_lstQuestions", typeParameter, partitionIDParameter, systemIDParameter, tagsParameter, textParameter, createdByParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_VideoForFirst(Nullable<int> sectionID, Nullable<int> courseID, string userID)
        {
            var sectionIDParameter = sectionID.HasValue ?
                new ObjectParameter("SectionID", sectionID) :
                new ObjectParameter("SectionID", typeof(int));
    
            var courseIDParameter = courseID.HasValue ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_VideoForFirst", sectionIDParameter, courseIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<sp_lstVideos_Result> sp_lstVideos(string studentID, string courseID, string packageID, string sectionID, string videoID, string videoType)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var courseIDParameter = courseID != null ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(string));
    
            var packageIDParameter = packageID != null ?
                new ObjectParameter("PackageID", packageID) :
                new ObjectParameter("PackageID", typeof(string));
    
            var sectionIDParameter = sectionID != null ?
                new ObjectParameter("SectionID", sectionID) :
                new ObjectParameter("SectionID", typeof(string));
    
            var videoIDParameter = videoID != null ?
                new ObjectParameter("VideoID", videoID) :
                new ObjectParameter("VideoID", typeof(string));
    
            var videoTypeParameter = videoType != null ?
                new ObjectParameter("VideoType", videoType) :
                new ObjectParameter("VideoType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstVideos_Result>("sp_lstVideos", studentIDParameter, courseIDParameter, packageIDParameter, sectionIDParameter, videoIDParameter, videoTypeParameter);
        }
    
        public virtual ObjectResult<sp_rptReultReport_Result> sp_rptReultReport(Nullable<int> universityID, Nullable<int> paperID, string sectionID, string studentID, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var universityIDParameter = universityID.HasValue ?
                new ObjectParameter("UniversityID", universityID) :
                new ObjectParameter("UniversityID", typeof(int));
    
            var paperIDParameter = paperID.HasValue ?
                new ObjectParameter("PaperID", paperID) :
                new ObjectParameter("PaperID", typeof(int));
    
            var sectionIDParameter = sectionID != null ?
                new ObjectParameter("SectionID", sectionID) :
                new ObjectParameter("SectionID", typeof(string));
    
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rptReultReport_Result>("sp_rptReultReport", universityIDParameter, paperIDParameter, sectionIDParameter, studentIDParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<sp_rptQuestionStats_Result> sp_rptQuestionStats(Nullable<int> questionPaperID, Nullable<int> systemID, Nullable<int> top)
        {
            var questionPaperIDParameter = questionPaperID.HasValue ?
                new ObjectParameter("QuestionPaperID", questionPaperID) :
                new ObjectParameter("QuestionPaperID", typeof(int));
    
            var systemIDParameter = systemID.HasValue ?
                new ObjectParameter("SystemID", systemID) :
                new ObjectParameter("SystemID", typeof(int));
    
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rptQuestionStats_Result>("sp_rptQuestionStats", questionPaperIDParameter, systemIDParameter, topParameter);
        }
    
        public virtual ObjectResult<sp_GetStudentsWithLastOnline_Result> sp_GetStudentsWithLastOnline(Nullable<int> dayFrom, Nullable<int> dayTo)
        {
            var dayFromParameter = dayFrom.HasValue ?
                new ObjectParameter("DayFrom", dayFrom) :
                new ObjectParameter("DayFrom", typeof(int));
    
            var dayToParameter = dayTo.HasValue ?
                new ObjectParameter("DayTo", dayTo) :
                new ObjectParameter("DayTo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetStudentsWithLastOnline_Result>("sp_GetStudentsWithLastOnline", dayFromParameter, dayToParameter);
        }
    
        public virtual ObjectResult<sp_lstQuestionPapers_Result> sp_lstQuestionPapers(string forStudent, Nullable<bool> mockTest)
        {
            var forStudentParameter = forStudent != null ?
                new ObjectParameter("ForStudent", forStudent) :
                new ObjectParameter("ForStudent", typeof(string));
    
            var mockTestParameter = mockTest.HasValue ?
                new ObjectParameter("MockTest", mockTest) :
                new ObjectParameter("MockTest", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstQuestionPapers_Result>("sp_lstQuestionPapers", forStudentParameter, mockTestParameter);
        }
    
        public virtual ObjectResult<sp_MyCourses_Result> sp_MyCourses(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MyCourses_Result>("sp_MyCourses", studentIDParameter);
        }
    
        public virtual ObjectResult<sp_MySections_Result> sp_MySections(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MySections_Result>("sp_MySections", studentIDParameter);
        }
    
        public virtual ObjectResult<sp_lstTickets_Result> sp_lstTickets(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, string status, string student, string issuedTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var studentParameter = student != null ?
                new ObjectParameter("Student", student) :
                new ObjectParameter("Student", typeof(string));
    
            var issuedToParameter = issuedTo != null ?
                new ObjectParameter("IssuedTo", issuedTo) :
                new ObjectParameter("IssuedTo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstTickets_Result>("sp_lstTickets", dateFromParameter, dateToParameter, statusParameter, studentParameter, issuedToParameter);
        }
    
        public virtual ObjectResult<sp_DashBoardCounts_Result> sp_DashBoardCounts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DashBoardCounts_Result>("sp_DashBoardCounts");
        }
    
        public virtual ObjectResult<sp_GetDevicesNotification_Result> sp_GetDevicesNotification(string universityIDs, string packageIDs)
        {
            var universityIDsParameter = universityIDs != null ?
                new ObjectParameter("UniversityIDs", universityIDs) :
                new ObjectParameter("UniversityIDs", typeof(string));
    
            var packageIDsParameter = packageIDs != null ?
                new ObjectParameter("PackageIDs", packageIDs) :
                new ObjectParameter("PackageIDs", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDevicesNotification_Result>("sp_GetDevicesNotification", universityIDsParameter, packageIDsParameter);
        }
    
        public virtual ObjectResult<sp_GetNotifications_Result> sp_GetNotifications(string studentID, Nullable<bool> onlyPend)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            var onlyPendParameter = onlyPend.HasValue ?
                new ObjectParameter("OnlyPend", onlyPend) :
                new ObjectParameter("OnlyPend", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetNotifications_Result>("sp_GetNotifications", studentIDParameter, onlyPendParameter);
        }
    
        public virtual ObjectResult<sp_lstRequests_Result> sp_lstRequests(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, Nullable<int> type, string requestFor)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            var requestForParameter = requestFor != null ?
                new ObjectParameter("RequestFor", requestFor) :
                new ObjectParameter("RequestFor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstRequests_Result>("sp_lstRequests", dateFromParameter, dateToParameter, typeParameter, requestForParameter);
        }
    
        public virtual ObjectResult<sp_lstStudents_Result> sp_lstStudents(string text, Nullable<int> type, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lstStudents_Result>("sp_lstStudents", textParameter, typeParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<sp_TestsPerformance_Result> sp_TestsPerformance(string studentID)
        {
            var studentIDParameter = studentID != null ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TestsPerformance_Result>("sp_TestsPerformance", studentIDParameter);
        }
    }
}
