//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BlogPost
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Slug { get; set; }
        public string BlogContent { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public string Category { get; set; }
        public string Tags { get; set; }
        public string FeaturedImage { get; set; }
        public Nullable<int> SortID { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
