//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserLogins
    {
        public long ID { get; set; }
        public string DeviceID { get; set; }
        public string UserID { get; set; }
        public Nullable<bool> IsLocalStorage { get; set; }
        public Nullable<bool> IsCookie { get; set; }
        public string IpAddress { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
