//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FileItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_FileItems()
        {
            this.Files = new HashSet<tbl_FileItems>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string MimeType { get; set; }
        public string Path { get; set; }
        public bool IsFolder { get; set; }
        public System.DateTime CDate { get; set; }
        public System.DateTime MDate { get; set; }
        public Nullable<int> PackID { get; set; }
        public Nullable<int> FileId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FileItems> Files { get; set; }
        public virtual tbl_FileItems File { get; set; }
        public virtual tbl_Package tbl_Package { get; set; }
    }
}
