//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TicketReply
    {
        public int ID { get; set; }
        public Nullable<int> Ticket_ID { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string ReplyBody { get; set; }
        public string SentTo { get; set; }
        public Nullable<System.DateTime> SendDT { get; set; }
        public string SendBy { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual tbl_Ticket tbl_Ticket { get; set; }
    }
}
