//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Request
    {
        public int RequestID { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int Duration { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public string StudentEmail { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> PackageDurationID { get; set; }
        public string Payment { get; set; }
        public string TeacherFid { get; set; }
        public string RequestFor { get; set; }
        public Nullable<int> ExamAttemptID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tbl_Courses tbl_Courses { get; set; }
        public virtual tbl_Package tbl_Package { get; set; }
        public virtual tbl_Section tbl_Section { get; set; }
    }
}
