//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserDevices
    {
        public int ID { get; set; }
        public string DeviceID { get; set; }
        public string UserID { get; set; }
        public string DeviceName { get; set; }
        public string UserAgent { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public string IpAddress { get; set; }
        public Nullable<bool> IsApp { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
    }
}
