//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SectionSub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SectionSub()
        {
            this.tbl_Video = new HashSet<tbl_Video>();
        }
    
        public int ID { get; set; }
        public string SectionSub_Name { get; set; }
        public int Course_Fid { get; set; }
        public int Section_Fid { get; set; }
        public Nullable<int> SortID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tbl_Courses tbl_Courses { get; set; }
        public virtual tbl_Section tbl_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Video> tbl_Video { get; set; }
    }
}
