//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Exam()
        {
            this.tbl_ExamDetail = new HashSet<tbl_ExamDetail>();
        }
    
        public int ExamID { get; set; }
        public string ExamTitle { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Thumbnail { get; set; }
        public string TopicsCovered { get; set; }
        public string PackageIDs { get; set; }
        public string CourseIDs { get; set; }
        public string Tags { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> DifficultyLevel { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ExamDetail> tbl_ExamDetail { get; set; }
    }
}
