//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuestionPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_QuestionPaper()
        {
            this.tbl_ExamDetail = new HashSet<tbl_ExamDetail>();
            this.tbl_QuestionPaperDetail = new HashSet<tbl_QuestionPaperDetail>();
            this.tbl_ResultMaster = new HashSet<tbl_ResultMaster>();
        }
    
        public int PaperID { get; set; }
        public string PaperTitle { get; set; }
        public Nullable<int> Marks { get; set; }
        public string UniversityID { get; set; }
        public Nullable<int> PassPer { get; set; }
        public Nullable<int> Time { get; set; }
        public string Thumbnail { get; set; }
        public string TopicsCovered { get; set; }
        public string PackageIDs { get; set; }
        public string SectionIDs { get; set; }
        public string CourseIDs { get; set; }
        public string Notes { get; set; }
        public string Tags { get; set; }
        public Nullable<int> DifficultyLevel { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public Nullable<System.DateTime> StartDT { get; set; }
        public Nullable<System.DateTime> ExpiryDT { get; set; }
        public Nullable<System.DateTime> AnswerDT { get; set; }
        public Nullable<int> MockTestType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ExamDetail> tbl_ExamDetail { get; set; }
        public virtual tbl_QuestionPaper tbl_QuestionPaper1 { get; set; }
        public virtual tbl_QuestionPaper tbl_QuestionPaper2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuestionPaperDetail> tbl_QuestionPaperDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ResultMaster> tbl_ResultMaster { get; set; }
    }
}
