//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CourseDetails
    {
        public int CourseDetail_ID { get; set; }
        public string CourseDetail_Body { get; set; }
        public Nullable<int> Course_Fid { get; set; }
    
        public virtual tbl_Courses tbl_Courses { get; set; }
    }
}
