//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EnrollmentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_EnrollmentMaster()
        {
            this.tbl_EnrollmentDetail = new HashSet<tbl_EnrollmentDetail>();
            this.tbl_StudentInstallments = new HashSet<tbl_StudentInstallments>();
        }
    
        public int Enrollment_Id { get; set; }
        public System.DateTime Enrollment_Date { get; set; }
        public string Enrollment_Status { get; set; }
        public decimal Enrollment_Price { get; set; }
        public Nullable<System.DateTime> Enrollment_EndDate { get; set; }
        public string TeacherFid { get; set; }
        public Nullable<int> CouponID { get; set; }
        public Nullable<int> Enrollment_No { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> PackageDurationFid { get; set; }
        public string StudentFid { get; set; }
        public Nullable<bool> ByRequest { get; set; }
        public Nullable<bool> ByManual { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public Nullable<bool> ByExtension { get; set; }
        public Nullable<int> ExamAttemptID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual tbl_Coupon tbl_Coupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EnrollmentDetail> tbl_EnrollmentDetail { get; set; }
        public virtual tbl_PackageDuration tbl_PackageDuration { get; set; }
        public virtual tbl_Package tbl_Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_StudentInstallments> tbl_StudentInstallments { get; set; }
    }
}
