//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentNotif
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_StudentNotif()
        {
            this.tbl_SeenNotif = new HashSet<tbl_SeenNotif>();
        }
    
        public int ID { get; set; }
        public string UniversityIds { get; set; }
        public string PackageIds { get; set; }
        public string Description { get; set; }
        public string MessageTitle { get; set; }
        public string MaessageBody { get; set; }
        public string Banner { get; set; }
        public string Status { get; set; }
        public string PicturePath { get; set; }
        public Nullable<bool> IsPush { get; set; }
        public Nullable<bool> IsPopup { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> SendAt { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SeenNotif> tbl_SeenNotif { get; set; }
    }
}
