//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Reminder
    {
        public int RemID { get; set; }
        public string Reminder { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
