//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConversationReply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ConversationReply()
        {
            this.tbl_ConversationMedia = new HashSet<tbl_ConversationMedia>();
        }
    
        public long ID { get; set; }
        public Nullable<int> ConvID { get; set; }
        public string UserID { get; set; }
        public string ReplyBody { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
        public Nullable<System.DateTime> ReadAt { get; set; }
        public string Status { get; set; }
    
        public virtual tbl_Conversation tbl_Conversation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ConversationMedia> tbl_ConversationMedia { get; set; }
    }
}
