//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Conversation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Conversation()
        {
            this.tbl_ConversationReply = new HashSet<tbl_ConversationReply>();
        }
    
        public int ConvID { get; set; }
        public string UserID_Two { get; set; }
        public string UserID_One { get; set; }
        public string Status { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public string Title { get; set; }
        public string Descriptiom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ConversationReply> tbl_ConversationReply { get; set; }
    }
}
