//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DailyReport
    {
        public int ID { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserFid { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public Nullable<System.DateTime> ModifyDT { get; set; }
    
        public virtual tbl_DailyReportUsers tbl_DailyReportUsers { get; set; }
    }
}
