//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string SponserProfession { get; set; }
        public string FatherEmail { get; set; }
        public string FatherProfession { get; set; }
        public string User_FatherName { get; set; }
        public string Notes { get; set; }
        public string User_Pic { get; set; }
        public string User_AspUser { get; set; }
        public Nullable<int> Allowed_PC_Dev { get; set; }
        public Nullable<int> Allowed_Mob_Dev { get; set; }
        public Nullable<int> OccupationID { get; set; }
        public Nullable<int> InstituteID { get; set; }
        public string CNIC { get; set; }
        public string YearOfMBBS { get; set; }
        public string ExamType { get; set; }
        public string User_Mobile { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Institute { get; set; }
        public string JobLocation { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string City { get; set; }
        public string CNICFront { get; set; }
        public string CNICBack { get; set; }
        public string StuCardFront { get; set; }
        public string StuCardBack { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> MockTestType { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tbl_Master tbl_Master { get; set; }
        public virtual tbl_Master tbl_Master1 { get; set; }
    }
}
