//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EnrollmentDetail
    {
        public int ID { get; set; }
        public Nullable<int> EnrollmentID { get; set; }
        public Nullable<int> Section_Fid { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<bool> IsExpired { get; set; }
    
        public virtual tbl_Courses tbl_Courses { get; set; }
        public virtual tbl_EnrollmentMaster tbl_EnrollmentMaster { get; set; }
        public virtual tbl_Section tbl_Section { get; set; }
    }
}
