//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuestionPaperDetail
    {
        public int ID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> PaperID { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual tbl_Question tbl_Question { get; set; }
        public virtual tbl_QuestionPaper tbl_QuestionPaper { get; set; }
    }
}
