//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ResultMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ResultMaster()
        {
            this.tbl_ResultDetail = new HashSet<tbl_ResultDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string TrialStudent { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> QuestionPaperID { get; set; }
        public Nullable<int> ObtainedMarks { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public string Mode { get; set; }
        public Nullable<int> TimeElapsed { get; set; }
        public Nullable<int> TimeGiven { get; set; }
        public Nullable<bool> AllowReopen { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tbl_QuestionPaper tbl_QuestionPaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ResultDetail> tbl_ResultDetail { get; set; }
    }
}
