//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ResultDetail
    {
        public int ID { get; set; }
        public Nullable<int> ResultID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> TimeSpent { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsTrue { get; set; }
    
        public virtual tbl_Question tbl_Question { get; set; }
        public virtual tbl_ResultMaster tbl_ResultMaster { get; set; }
    }
}
