//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_StudentGroup()
        {
            this.tbl_StudentGroupDetail = new HashSet<tbl_StudentGroupDetail>();
        }
    
        public int Id { get; set; }
        public string GroupTitle { get; set; }
        public string Pic { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_StudentGroupDetail> tbl_StudentGroupDetail { get; set; }
    }
}
