//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentInstallments
    {
        public int ID { get; set; }
        public Nullable<int> EnrollmentID { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> InstallmentDate { get; set; }
        public Nullable<int> InstallmentNo { get; set; }
        public string StudentID { get; set; }
        public Nullable<decimal> InstallmentPrice { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> PkgDuration { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tbl_EnrollmentMaster tbl_EnrollmentMaster { get; set; }
        public virtual tbl_Package tbl_Package { get; set; }
    }
}
