//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BookMistakes
    {
        public int Id { get; set; }
        public string BookEdition { get; set; }
        public string BookName { get; set; }
        public string QuestionNo { get; set; }
        public string PageNo { get; set; }
        public string Subject { get; set; }
        public string Detail { get; set; }
        public string PicPath { get; set; }
        public string Correction { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
    }
}
