//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Progress
    {
        public int Video_Fid { get; set; }
        public string Student_Fid { get; set; }
        public Nullable<System.DateTime> LastOpenDT { get; set; }
        public Nullable<int> ScreenTime { get; set; }
        public Nullable<bool> isCompleted { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tbl_Video tbl_Video { get; set; }
    }
}
