//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Notes
    {
        public int Id { get; set; }
        public Nullable<int> FID { get; set; }
        public string Notes { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string StudentID { get; set; }
    }
}
