//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Options
    {
        public int ID { get; set; }
        public string OptionDetail { get; set; }
        public string OptionText { get; set; }
        public Nullable<int> Question_Id { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
    
        public virtual tbl_Question tbl_Question { get; set; }
    }
}
