//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Coupon()
        {
            this.tbl_EnrollmentMaster = new HashSet<tbl_EnrollmentMaster>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CouponSecret { get; set; }
        public Nullable<int> SectionID { get; set; }
        public bool IsActive { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> DiscountPer { get; set; }
        public Nullable<int> NoOfUses { get; set; }
        public Nullable<int> CourseFid { get; set; }
        public Nullable<bool> ForCourse { get; set; }
        public string CreatedBy { get; set; }
        public string CouponName { get; set; }
        public Nullable<int> RemUses { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tbl_Courses tbl_Courses { get; set; }
        public virtual tbl_Section tbl_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EnrollmentMaster> tbl_EnrollmentMaster { get; set; }
    }
}
