//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Video()
        {
            this.tbl_Comment = new HashSet<tbl_Comment>();
            this.tbl_Progress = new HashSet<tbl_Progress>();
        }
    
        public int Video_Id { get; set; }
        public string Video_Name { get; set; }
        public string Video_ShortDescription { get; set; }
        public Nullable<decimal> Video_Length { get; set; }
        public string Video_Path { get; set; }
        public Nullable<int> SectionSub_Fid { get; set; }
        public Nullable<int> Section_Fid { get; set; }
        public Nullable<int> Course_Fid { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> SortID { get; set; }
        public string Video_Tags { get; set; }
        public string Difficulty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Comment> tbl_Comment { get; set; }
        public virtual tbl_Courses tbl_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Progress> tbl_Progress { get; set; }
        public virtual tbl_Section tbl_Section { get; set; }
        public virtual tbl_SectionSub tbl_SectionSub { get; set; }
    }
}
