//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentGroupDetail
    {
        public int Id { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string StudentID { get; set; }
        public Nullable<bool> IsLeader { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tbl_StudentGroup tbl_StudentGroup { get; set; }
    }
}
