//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Document
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public string Title { get; set; }
        public string Doc_Form { get; set; }
        public string Doc_Path { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Fid { get; set; }
    }
}
