//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Question()
        {
            this.tbl_Options = new HashSet<tbl_Options>();
            this.tbl_QuestionPaperDetail = new HashSet<tbl_QuestionPaperDetail>();
            this.tbl_ResultDetail = new HashSet<tbl_ResultDetail>();
        }
    
        public int Question_Id { get; set; }
        public string Question { get; set; }
        public string AnsExplain { get; set; }
        public string Answer { get; set; }
        public string Tags { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Marks { get; set; }
        public Nullable<int> DifficultyLevel { get; set; }
        public int Type { get; set; }
        public Nullable<int> Section_Fid { get; set; }
        public Nullable<int> VideoID { get; set; }
        public Nullable<int> Course_Fid { get; set; }
        public Nullable<bool> IsMultiAns { get; set; }
        public Nullable<bool> IsPopular { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> PartitionID { get; set; }
        public Nullable<int> SystemID { get; set; }
    
        public virtual tbl_Courses tbl_Courses { get; set; }
        public virtual tbl_Master tbl_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Options> tbl_Options { get; set; }
        public virtual tbl_QuestionPartition tbl_QuestionPartition { get; set; }
        public virtual tbl_Section tbl_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuestionPaperDetail> tbl_QuestionPaperDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ResultDetail> tbl_ResultDetail { get; set; }
        public virtual tbl_QuestionSystem tbl_QuestionSystem { get; set; }
    }
}
