//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comment
    {
        public int ID { get; set; }
        public string Comment_Body { get; set; }
        public Nullable<System.DateTime> Comment_Date { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> Video_Fid { get; set; }
        public string UserFid { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDT { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tbl_Video tbl_Video { get; set; }
    }
}
