//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tutorial
    {
        public int TutorialID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string VideoLink { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public Nullable<bool> IsPopular { get; set; }
    
        public virtual tbl_Master tbl_Master { get; set; }
    }
}
