//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Chapter
    {
        public int ChapterID { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public string Title { get; set; }
        public string ChapterContent { get; set; }
        public Nullable<int> SortID { get; set; }
    
        public virtual tbl_Courses tbl_Courses { get; set; }
    }
}
