//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Meeting()
        {
            this.tbl_MeetingVideo = new HashSet<tbl_MeetingVideo>();
        }
    
        public int ID { get; set; }
        public Nullable<long> MeetingNo { get; set; }
        public Nullable<int> Duration { get; set; }
        public string PackageIDs { get; set; }
        public string CourseIDs { get; set; }
        public string Topic { get; set; }
        public string JoinUrl { get; set; }
        public string Status { get; set; }
        public string Password { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MeetingVideo> tbl_MeetingVideo { get; set; }
    }
}
