//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserDevRemReq
    {
        public int ID { get; set; }
        public string DeviceID { get; set; }
        public string UserID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
    }
}
