//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PackageDetail
    {
        public int DetailID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string Type { get; set; }
        public string Paper { get; set; }
    
        public virtual tbl_Courses tbl_Courses { get; set; }
        public virtual tbl_Package tbl_Package { get; set; }
    }
}
