//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Aid_Made_Easy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudetsList
    {
        public string Text { get; set; }
        public string Value { get; set; }
        public string Role { get; set; }
        public string User_Name { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
